server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Assignment
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false